version: 1.3.2.65{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
environment:
  NHV_VERSION: "1.3.2.4000"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(NHV_VERSION)
  assembly_file_version: '{version}'
  assembly_informational_version: "{version}-%APPVEYOR_REPO_COMMIT%"
before_build:
  - cmd: |
      setlocal enabledelayedexpansion
      setlocal EnableExtensions
before_package:
  - cmd: |
      nuget pack -Version %APPVEYOR_BUILD_VERSION% "NHibernate.Validator\NHibernate.Validator.pt.nuspec" -Properties "Configuration=Release;Platform=AnyCPU" -OutputDirectory "C:\Users\appveyor\AppData\Local\Temp\1"
      nuget pack -Version %APPVEYOR_BUILD_VERSION% "NHibernate.Validator\NHibernate.Validator.ca.nuspec" -Properties "Configuration=Release;Platform=AnyCPU" -OutputDirectory "C:\Users\appveyor\AppData\Local\Temp\1"
      appveyor PushArtifact C:\Users\appveyor\AppData\Local\Temp\1\NHibernate.Validator.ca.%APPVEYOR_BUILD_VERSION%.nupkg
      appveyor PushArtifact C:\Users\appveyor\AppData\Local\Temp\1\NHibernate.Validator.pt.%APPVEYOR_BUILD_VERSION%.nupkg
build:
  project: NHibernate.Validator.sln
  publish_nuget: true
  publish_nuget_symbols: false
  use_snupkg_format: false
  verbosity: normal
deploy:
  - provider: NuGet
    api_key:
      secure: eRd7Xvy1n8XML+TP4zZ2PmEUAJ5hRWEMD42jmoDCnMfikICsGiVdIyKYAg0GE9ch
    on:
      branch: master
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
