version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
#install:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-nuget-3-3-0.ps1'))
before_build:
  - cmd: |
      setlocal enabledelayedexpansion
      setlocal EnableExtensions
before_package:
  - cmd: | 
      mv NHibernate.Validator\bin\Release\ca\NHibernate.Validator.ExtraCultures.resources.dll NHibernate.Validator\bin\Release\ca\NHibernate.Validator.resources.dll
      mv NHibernate.Validator\bin\Release\pt\NHibernate.Validator.ExtraCultures.resources.dll NHibernate.Validator\bin\Release\pt\NHibernate.Validator.resources.dll
build:
  publish_nuget: true
  publish_nuget_symbols: false
  use_snupkg_format: false
  verbosity: normal
deploy:
  - provider: NuGet
    api_key:
      secure: eRd7Xvy1n8XML+TP4zZ2PmEUAJ5hRWEMD42jmoDCnMfikICsGiVdIyKYAg0GE9ch
    on:
      branch: master
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true